spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_bossabox
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    defaultModelsExpandDepth: -1
    docExpansion: none
  packages-to-scan: com.bossabox.api.controller
  paths-to-match: /api/**